#+TITLE: PHIL 971 - Kant & Kantianism on Rational Agency
#+DATE: July 2, 2020
#+AUTHOR: Colin McLear
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport archive nohugo
#+TODO: TODO NEXT | DONE CANCELED
#+TODO: DRAFT | DONE CANCELED
#+LANGUAGE: en
#+LATEX_HEADER: \usepackage[English]{babel}
#+OPTIONS: '":t

* Course Outline

* Website
** Pages
:PROPERTIES:
:EXPORT_HUGO_SECTION: ./
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :author false :toc false
:END:
*** Welcome!
:PROPERTIES:
:EXPORT_FILE_NAME: home
:END:

This is the homepage for *PHIL 971* – Kant (and kantianism) on Rational Agency


Kant famously considers moral agency to consist in acting from a grasp of rational principles as such. But what is a rational principle and what is it to act from such a principle? In this seminar we'll look at how Kant answers these questions, and evaluate the theory of rational agency that results. We'll also look at the reception of Kant's position in contemporary Anglophone philosophy, particularly in the work of Frankfurt, Korsgaard, Velleman, Reath, and Herman. Some related questions we'll be trying to find answers to include:

- How does Kant conceive of the connection between rational action and free action? 
- What kind of metaphysical commitments does Kant build into his conception of
  rational action? Do any of these commitments seem plausible today? 
- What is the importance of the capacity for self-consciousness with respect to being rational?

*** Schedule
:PROPERTIES:
:EXPORT_FILE_NAME: schedule
:EXPORT_HUGO_MENU: :menu main
:END:

This is a tentative schedule. Check the [[https://phil971.colinmclear.net/assignments][assignments]] page for the most current
information.

| Week | Date  | Topic                            |
|------+-------+----------------------------------|
|    1 | 8/18  | Problem Setup/Kant's Agent       |
|    2 | 8/25  | Kant's Free Agent                |
|    3 | 9/1   | Enkratic Rationality             |
|    4 | 9/8   | Inference & Agency               |
|    5 | 9/15  | Reason & Principles              |
|    6 | 9/22  | A Compatibilist Kant?            |
|    7 | 9/29  | The Frankfurtian Background      |
|    8 | 10/6  | Other Kantian Compatibilists     |
|    9 | 10/13 | Paper Meetings                   |
|   10 | 10/20 | Self-Consciousness & Rationality |
|   11 | 10/27 | Rational Teleology               |
|   12 | 11/3  | Is Rationality Transformative?   |
|   13 | 11/10 | Prep for Karl Schafer            |
|   14 | 11/17 | Karl Schafer (guest)             |
|------+-------+----------------------------------|



*** Paper Topics
:PROPERTIES:
:EXPORT_FILE_NAME: paper-topics
:EXPORT_HUGO_MENU: :menu main
:END:

Here are some possible topics for papers. You are welcome to write on something else (or on some modified topic related to one of the options below), but please discuss this with me first. The first draft of the paper is due *Friday, November 16th*. The final draft is due *Friday, December 7th*.  

*** Resources
:PROPERTIES:
:EXPORT_FILE_NAME: resources
:EXPORT_HUGO_MENU: :menu main
:END:

**** Philosophy Links
- [[http://plato.stanford.edu][Stanford Encyclopedia of Philosophy]]
- [[http://www.iep.utm.edu/][Internet Encyclopedia of Philosophy]]
- [[http://philpapers.org][PhilPapers]]
  
**** Reading & Writing Philosophy
- [[http://www.jimpryor.net/teaching/vocab/index.html][Philosophical Terms & Methods]]
- [[http://www.jimpryor.net][Jim Pryor's]] guides to [[http://www.jimpryor.net/teaching/guidelines/reading.html][reading]] and [[http://www.jimpryor.net/teaching/guidelines/writing.html][writing]] philosophy
- [[http://philosophy.hku.hk/think/][Critical Thinking]]
- [[http://owl.english.purdue.edu/owl/][Purdue Online Writing Lab]] 
- [[http://writingproject.fas.harvard.edu/files/hwp/files/philosophical_writing.pdf][A Guide to Philosophical Writing]]
- [[https://www.dropbox.com/s/lyods0bt22x8u6l/ThesisOverview.pdf?dl=0][Writing a Thesis Statement]]
- [[https://www.dropbox.com/s/eaggc570nfu6nqa/PaperStructure.pdf?dl=0][Philosophy Paper Structure]]

**** Kant Related Links
- [[http://kantpapers.org][KantPapers]]
- [[http://www.manchester.edu/kant/Home/index.htm][Kant in the Classroom]] (Steve Naragon)
- [[http://staffweb.hkbu.edu.hk/ppp/Kant.html][Kant on the Web]] (Steve Palmquist)
- [[http://publish.uwo.ca/~cdyck5/UWOKRG/kantsbooks.html][Kant's Books]] (UWO Kant Research Group)
- [[https://dspace.ut.ee/handle/10062/42108][Kants Handexemplar von Meiers Auszug aus der Vernunftlehre]] (University of Tartu)
- [[https://www.philosophie.fb05.uni-mainz.de/forschungsstellen-und-weitere-einrichtungen/fs_kant/][Kant-Forschungsstelle]]
- [[http://earlymoderntexts.com][Early Modern Philosophy Texts]]
- [[https://korpora.zim.uni-duisburg-essen.de/Kant/verzeichnisse-gesamt.html][Kant Akademieausgabe (Courtesy of Universität Duisburg-Essen)]]
- [[http://knb.mpiwg-berlin.mpg.de/kant/home][Database of Kant's concepts for a theory of nature]]

**** Sources for online German texts
- [[http://gso.gbv.de/DB=1.28/SET=1/TTL=1/][VD17]]
- [[http://www.zvdd.de/startseite/][ZVDD]]
- [[http://kvk.bibliothek.kit.edu/?digitalOnly=0&embedFulltitle=0&newTab=0][KVK]]
- [[http://digital-beta.staatsbibliothek-berlin.de][Digitalisierte Sammlungen (Berlin)]]
- [[https://www.deutsche-digitale-bibliothek.de][Deutsche Digitale Bibliothek]]

  

*** Contact
:PROPERTIES:
:EXPORT_FILE_NAME: contact
:EXPORT_HUGO_MENU: :menu main
:END:

Dr. Colin McLear\\
Office: Working Remotely\\
Office Hours: Th 1:00-3:00 and by appointment\\
Email: [[mailto:mclear@unl.edu][mclear@unl.edu]]

Email is the best way to reach me. I answer emails as soon as I can, but
primarily only on /weekdays/. 

** Assignments
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :author false :toc false :type post
:EXPORT_HUGO_WEIGHT: -100
:EXPORT_HUGO_SECTION: assignments
:END:
*** DONE Week 1 - Kant’s Agent
SCHEDULED: <2020-08-18 Tue>
:PROPERTIES:
:EXPORT_HUGO_TAGS: action agency causality metaphysics substance
:EXPORT_FILE_NAME: week1
:END:

This week we’ll go over the basic structure and themes of the course and then sketch 
Kant’s view of agency. We’ll look in particular at his conception of causation and
the way in which an agent is understood as a substance with causal powers to effect
change in itself or other beings. 

**** Readings
- Kant’s Critical project
   - CPR: [[/materials/readings/CPR-preface-and-introduction.pdf][Preface & Introduction]] (Second edition)
   - CPJ: [[/materials/readings/CPJ-FI-III.pdf][First Introduction, §3]]
- Watkins, [[/materials/readings/watkins-action.pdf][Kant on Action]]
- Stang, [[/materials/readings/stang-ground.pdf][Guide to Ground in the /Lectures on Metaphysics/]]


*** DRAFT Week 2 - Freedom & Agency
SCHEDULED: <2020-08-25 Tue>
:PROPERTIES:
:EXPORT_HUGO_TAGS: action agency causality freedom metaphysics substance
:EXPORT_FILE_NAME: week2
:END:

This week we’ll start looking more closely at Kant’s conception of free action. We’ll
discuss the differences between 'practical’ and 'transcendental’ freedom and why the
former might depend on the latter. 

**** Readings
- From Kant:
   - CPR: The Third Antinomy (excerpt, A532/B560–A558/B586)
   - CPR: The Canon of Pure Reason (excerpt, A800/B828–A804/B832)
   - CPrR: Critical Elucidation of the Analytic of Pure Practical Reason (excerpt, 5:94-102)


*** DRAFT Week 3 - Freedom & Control
SCHEDULED: <2020-09-01 Tue>
:PROPERTIES:
:EXPORT_HUGO_TAGS: action agency causality control freedom 
:EXPORT_FILE_NAME: week3
:END:

Last week we started talking about Kant’s conception of free action. This week we’ll
try and get clearer as to the notion of ‘control’ that lies behind this conception of
free action. 

**** Readings
- McLear, Control

  
** Notes
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :author false :toc false :type post
:EXPORT_HUGO_SECTION: notes
:EXPORT_HUGO_PANDOC_CITATIONS: t
:EXPORT_HUGO_PAIRED_SHORTCODES: %mdshortcode myshortcode
:EXPORT_BIBLIOGRAPHY: /Users/roambot/Dropbox/Work/All.bib
:EXPORT_HUGO_WEIGHT: 0
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :link-citations true
:END:

These are notes to supplement student reading. Their aim is to be introductory
and to raise questions for discussion. 



*** DONE Kant on the Synthetic A Priori
SCHEDULED: <2020-08-18 Tue>
:PROPERTIES:
:EXPORT_HUGO_TAGS: judgment analytic/synthetic truth "a priori"
:EXPORT_FILE_NAME: kant-on-synthetic-a-priori
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type post :nocite '(@allison1973 @allison2004 @beck1955 @beck1956 @beck1978d @beck1969 @gardner1999 @lovejoy1906a @vancleve1999 @proops2005 @hogan2013)
:END:
 
#  1.  The distinction between pure and empirical knowledge
#  2.  We have some items of a priori knowledge, and even the common
#      understanding is never without them
#  3.  Philosophy needs a science to show that there can be a priori
#      knowledge, and to establish its principles and its scope
#  4.  The difference between analytic and synthetic judgments
#  5.  All theoretical sciences of reason contain synthetic a priori
#      judgments as principles
#  6.  The general problem of pure reason
#  7.  The idea and division of a special science called ‘critique of pure
#      reason’

[[http://plato.stanford.edu/entries/kant/][Immanuel Kant]] (1724--1804) was the most significant German philosopher of the
eighteenth century, and was a key figure in the [[http://plato.stanford.edu/entries/kant/][Enlightenment]]. He wrote most
of his most famous philosophical works relatively late in his professional
life, having only achieved a permanent position as professor in 1770, at the
age of forty-six. From 1781 to 1798 Kant published a series of tremendously
influential philosophical works, including the /Critique of Pure Reason/
(1781/​7), the /Groundwork of the Metaphysics of Morals/ (1785), the /Metaphysical
Foundations of Natural Science/ (1786), the /Critique of Practical Reason/
(1788), and the /Critique of the Power of Judgment/ (1790).

We'll be primarily focusing on Kant's project in the /Critique of Pure Reason/,
as well as the moral philosophy of the /Groundwork for the Metaphysics of
Morals/ and the /Critique of Practical Reason/. There are certain aspects of
Kant's project in the /Critique of Pure Reason/ that should be very familiar to
those with knowledge of prominent European philosophers of the 17th and 18th
centuries. For example, like Descartes, Locke, and Hume, Kant wishes to
articulate the nature and extent of human knowledge, and to do so in a manner
which proceeds from an analysis of the nature of human cognitive capacities.
Kant believes that human reason requires a ‘critique'---a kind of process of
self-examination or scrutiny---as to whether it is fit to provide us with
knowledge. Kant ultimately argues that human reason is not fit to provide us
with knowledge of a mind-independent reality transcending human experience. In
this sense Kant is deeply sympathetic with ‘empiricist' critiques by Locke,
Berkeley, and Hume of ‘rationalist' philosophers such as Descartes and
Leibniz.

However, Kant also argues that we have much deeper and more extensive
knowledge of the world we experience (or could possibly experience) than his
empiricist predecessors would allow. For example, Kant argues that we have
knowledge of necessary truths concerning aspects of the empirical world (such
as that every event in the empirical world has a cause), as well as truths
which are universal in scope or extent. Thus Kant articulates a view that is
directly opposed to the kinds of skeptical arguments Hume discusses in his
/Treatise/ and first /Enquiry/.

Kant thus thinks that we have knowledge of the necessary and universal laws
governing the empirical world---or more simple, "nature"---while he
nevertheless argues that we are almost wholly ignorant of the fundamental
reality which underlies or grounds the existence of the natural world. In
this way Kant combines various aspects of both the traditional rationalist and
empiricist positions. Like Locke and Hume, Kant thinks we must realize that
the boundaries of human knowledge stop at experience, and thus that we must be
extraordinarily circumspect concerning any claim made about what reality is
like independent of all human experience. But, like Descartes and Leibniz,
Kant thinks that central parts of human knowledge nevertheless exhibit
characteristics of necessity and universality, and that, contrary to Hume's
skeptical arguments, we can have good reason to think that they do.

Kant thus critiques pure reason in order to show its nature and limits, and
thereby curb the pretensions of various metaphysical systems articulated on
the basis of a firm faith that reason alone allows us to scrutinize the very
depths of reality. But Kant also argues that the legitimate domain of reason
is more extensive and more substantive than previous empiricist critiques had
allowed. In this way Kant salvages much of the prevailing Enlightenment
conception of reason as an organ for knowledge of the world.

Below I characterize some of the central aspects of Kant's epistemological
framework and how that framework significantly revolutionized our
understanding of the possible nature and extent of human knowledge.

**** Human Knowledge

***** The A Priori

A variety of philosophers from the Early Modern period (e.g. Descartes,
Leibniz, Hume) argue that there are kinds of knowledge that may be had just by
thinking, and that such forms of knowledge are universal and necessary in
scope. Hume's conception of knowledge made this especially clear. According to
Hume, knowledge of necessary and universal truths must be purely a function of
knowledge of the relations of ideas.

Kant agrees with Hume that a priori knowledge is independent of experience. In
fact, he sees it as definitive of 'pure' a priori knowledge that it be
completely independent of experience in the sense that its content is neither
derived from experience not justified by experience in its application. He
contrasts such knowledge with 'empirical' knowledge or knowledge a posteriori.
A priori knowledge may be more or less 'pure' according to whether or not the
concepts which make it up are themselves a priori knowable. Kant uses the
example 'every alteration has a cause' as an example of /impure/ a priori
knowledge, since the concept <alteration> is empirical.

One important point about Kant's use of 'independent' in describing the a
priori. Kant does not think that a priori knowledge is independent of
experience in the sense that one need not have /any/ experience in order to have
knowledge. On the contrary, Kant thinks that /all/ of our knowledge depends on
our having experience of some kind or another, though he doesn't think this
dependence entails that all our judgments are ultimately /justified/ by
experience. This is why Kant says that

#+BEGIN_QUOTE
  But although all our cognition commences with experience, yet it does
  not on that account all arise from experience. (CPR B1)
#+END_QUOTE

There seems to be two reasons for Kant's thinking this. First, we need
experience in order for our cognitive faculties to function and develop.
Second, we may need particular experiences in order to acquire empirical
concepts (e.g. red experiences in order to acquire the concept <red>). This is
what distinguishes pure from impure a priori judgments. Impure a priori
judgments are partially constituted by concepts whose content is in some way
derived from content given by the senses.

If a priori knowledge is, for Kant, knowledge that is (in some sense to
be further specified) /independent/ of experience, that fact is not the
only mark or indicator that some bit of knowledge is a priori. In
addition, Kant argues, any bit of knowledge that is necessary and/or
universal in scope is itself a priori.

#+BEGIN_QUOTE
  Necessity and strict universality are therefore secure indications" of
  an a priori cognition, and also belong together inseparably. But since
  in their use it is sometimes easier to show the empirical limitation
  in judgments than the contingency in them, or is often more plausible
  to show the unrestricted universality that we ascribe to a judgment
  than its necessity, it is advisable to employ separately these two
  criteria, each of which is in itself infallible. (CPR B4)
#+END_QUOTE
  

Kant argues that this conception of a priori knowledge is presupposed in many
empirical judgments as well as in particular sciences. He specifically points
to mathematics ('5+7=12') and to physical judgments ('every alteration has a
cause'). One of Kant's arguments against Humean skepticism is that all of our
empirical knowledge (even that knowledge which we think we have
unproblematically) presupposes a priori knowledge, which itself requires that
there be legitimate use of pure a priori concepts (i.e. concepts which cannot be
derived from any sense impression).

Kant thinks that there are many examples of judgments which we claim to know a
priori, but he is interested primarily in a specific subset of those which
constitute the subject matter of /metaphysics/---viz. judgments concerning God,
the soul (or mind), and immortality. One of Kant's primary aims is to
determine whether metaphysical knowledge is possible, and if it is possible,
what the extent and nature of that knowledge might be. This is what it means
when Kant says that he wishes to set metaphysics "on the secure path of a
science" (e.g. Bxvi). Metaphysical knowledge is problematic, Kant argues,
because unlike other forms of a priori knowledge, such as logic and
mathematics, it is not at all obvious which metaphysical judgments are in fact
correct and thus known, and which are merely thought to be so. This is
exemplified, Kant thinks, by the contentious disputes in which philosophers
have long been involved. Kant provides the following memorable description of
the sad plight of metaphysics. 

#+BEGIN_QUOTE
In metaphysics we have to retrace our path countless times, because we find
that it does not lead where we want to go, and it is so far from reaching
unanimity in the assertions of its adherents that it is rather a battlefield,
and indeed one that appears to be especially determined for testing one's
powers in mock combat; on this battlefield no combatant has ever gained the
least bit of ground, nor has any been able to base any lasting possession on
his victory. Hence there is no doubt that up to now the procedure of
metaphysics has been a mere groping, and what is the worst, a groping among
mere concepts. (Bxiv-xiv)
#+END_QUOTE 

Kant thus hopes that, by giving a critique of reason, he can demonstrate the
extent to which metaphysics might count as a science. As a secure science it
would rest on a secure set of claims and no longer be a "groping among mere
concepts."

***** The Analytic/Synthetic Distinction

A judgment is known (or knowable) a priori if it is known (or knowable)
independently of experience. Kant thinks that this is not the only dimension
according to which one can analyze a judgment. Kant also argues that all
judgments, in addition to being classifiable as either a priori or a
posteriori (or empirical), may also be classified as being either [[http://plato.stanford.edu/entries/analytic-synthetic/][analytic or
synthetic]].

An analytic judgment is one in which the predicate is ‘contained' in the
concept. One way of understanding this notion of ‘containment' is via a claim
about meaning. Accordingly, analytic judgments are those whose truth is known
merely in virtue of knowing the meaning or content of the concepts
constituting the judgment. For example, in the judgment ‘All bachelors are
unmarried' the concept <unmarried> is part of the meaning of <bachelor> and so
the truth of the judgment is grasped just by knowing the relevant meanings or
contents of its component concepts.

Kant also introduces several other markers of analyticity. In total Kant
provides us with four different marks of analyticity. He says that in an
analytic judgment the predicate is

1. ‘contained' within the subject
2. ‘identical' with the subject
3. analytic judgments are ones which are ‘explicative' rather than
   ‘ampliative'
4. analytic judgments are those knowable by means of application of the
   principle of non-contradiction

Which, if any of these markers is best thought of as the main characteristic
of an analytic judgment? This is a disputed issue (cf. @anderson2005;
@proops2005), though certainly, in all cases Kant is thinking of ‘atomic'
judgments of subject-predicate form.

***** The Synthetic A Priori

Kant argues, in ways similar to Locke, Hume, and Leibniz, that analytic
judgments are knowable a priori. Staying with the ‘containment' metaphor,
since the predicate is contained in the subject of an analytic judgment, there
is no need to look beyond the judgment to the world (so to speak) in order to
determine the truth value of the judgment. In this Kant is obviously in
agreement with Locke, Hume, and Leibniz. Kant agrees with his empiricist
predecessors in claiming that all a posteriori judgments are synthetic. Since
the predicate is adding something new to the subject we must look beyond the
judgment to the world---what we can experience---in order that we might
determine the relevant judgments truth or falsity. In non-empirical cases
(like the bachelor example above) the judgment's truth is determined by the
meanings of the concepts constituting it.

Kant's main innovation to the a priori/posteriori and analytic/synthetic
schemas is to note that the analytic a priori and the synthetic a posteriori
do not necessarily exhaust the realm of possible judgments. Here he
essentially can be understood to deny that "Hume's Fork" is an adequate
representation of the structure of human knowledge. According to Kant, there
are also /synthetic a priori/ judgments that are possible. Kant argues that
causal judgments are a clear example.

#+BEGIN_QUOTE
  it is easy to show that in human cognition there actually are such
  necessary and in the strictest sense universal, thus pure a priori
  judgments. If one wants an example from the sciences, one need only
  look at all the propositions of mathematics; if one would have one
  from the commonest use of the understanding, the proposition that
  every alteration must have a cause will do; indeed in the latter the
  very concept of a cause so obviously contains the concept of a
  necessity of connection with an effect and a strict universality of
  rule that it would be entirely lost if one sought, as Hume did, to
  derive it from a frequent association of that which happens with that
  which precedes and a habit (thus a merely subjective necessity) of
  connecting representations arising from that association (CPR B4-5)
#+END_QUOTE

#+BEGIN_QUOTE
  Take the proposition: "Everything that happens has its cause." In the
  concept of something that happens, I think, to be sure, of an
  existence that was preceded by a time, etc., and from that analytic
  judgments can be drawn. But the concept of a cause lies entirely
  outside that concept, and indicates something different than the
  concept of what happens in general, and is therefore not contained in
  the latter representation at all. How then do I come to say something
  quite different about that which happens in general, and to cognize
  the concept of cause as belonging to it, indeed necessarily, even
  though not contained in it? What is the unknown=X here on which the
  understanding depends when it believes itself to discover beyond the
  concept of A a predicate that is foreign to it yet which it
  nevertheless believes to be connected with it? (CPR B13-14)
#+END_QUOTE

Kant argues here that our judgments concerning events presuppose that they do
not just /occur/ but are /caused to occur/, that we know this to be true
necessarily and universally, and that we have no explanation of this fact
unless the judgments we make in such cases are synthetic a priori judgments.
The question remains, however, just how such synthetic a priori judgments
could be possibly true, much less known to be so. What is it that could link
the concepts in a subject-predicate judgment such that the truth of the
judgment holds necessarily and universally, while its nevertheless being true
that the predicate is not contained in the subject of the judgment, and thus
that the judgment is not analytic?

#+BEGIN_QUOTE
  Now the entire final aim of our speculative a priori cognition rests
  on such synthetic, i.e., ampliative principles; for the analytic ones
  are, to be sure, most important and necessary, but only for
  attaining that distinctness of concepts which is requisite for a
  secure and extended synthesis as a really new acquisition (CPR B13-14)
#+END_QUOTE

Kant argues that we need to explain how synthetic a priori judgments are
possible, and that the explanation of the possibility of significant portions
of our knowledge rests on this, including mathematics and natural science, as
well as the very possibility of metaphysics.

***** Mathematics and the Synthetic A Priori

Recall that for Hume, mathematical knowledge was a function merely of
knowledge of relations of ideas, in other words, that math is analytic
and a priori. Kant disputes this. Our mathematical knowledge is
certainly a priori, he thinks, but it is not explained in terms of
relations of ideas or concepts (i.e. in terms of containment or any of
the other marks of analyticity). Instead, Kant argues that mathematical
knowledge must be /synthetic/, but since it is necessary and universal,
also /a priori/. Here's how Kant puts the point in his /Prolegomena/:

#+BEGIN_QUOTE
  The essential feature of pure mathematical cognition, differentiating
  it from all other a priori cognition, is that it must throughout
  proceed not from concepts, but always and only through the
  construction of concepts (Critique, p. 713). Because pure mathematical
  cognition, in its propositions, must therefore go beyond the concept
  to that which is contained in the intuition corresponding to it, its
  propositions can and must never arise through the analysis of
  concepts, i.e., analytically, and so are one and all synthetic.
  (/Prolegomena/ 4:272, p. 20)
#+END_QUOTE

Kant uses two examples in his argument concerning mathematics. The first
is the judgment '7+5=12' and the second is the geometric judgment that
'the shortest distance between two points is a straight line'. Though
both judgments are knowable a priori, Kant thinks that in neither of
these two cases can we explain the truth of the judgments analytically.

#+BEGIN_QUOTE
  One might well at first think: that the proposition 7 + 5 = 12 is a
  purely analytic proposition that follows from the concept of a sum of
  seven and five according to the principle of contradiction. However,
  upon closer inspection, one finds that the concept of the sum of 7 and
  5 contains nothing further than the unification of the two numbers
  into one, through which by no means is thought what this single number
  may be that combines the two. The concept of twelve is in no way
  already thought because I merely think to myself this unification of
  seven and five, and I may analyze my concept of such a possible sum
  for as long as may be, still I will not meet with twelve therein.
  (/Prolegomena/ 4:268-9, p. 18)
#+END_QUOTE

Kant's argument here is that while it might be analytically true that
the sum of 7 and 5 is /a number/ (and also that it must be a /natural
number/), it is not clear from analysis alone that the sum is equal to
12, or any other pair of natural numbers which might sum to 12.

Kant seems to think that to the extent one finds the answer twelve
/obvious/ one is adverting, either explicitly or implicitly, to some
particular experience of adding units, such as counting on one's
fingers, or adding up objects (e.g. apples, chairs, blocks, etc.).

Also, if '7+5=12' is known analytically, then in thinking it one is
equivalently thinking of any or all the numbers which are equal to 12,
including /very large/ numbers (e.g. any numbers /m/ and /n/ which might yield 12).
This certainly doesn't reflect our experience when calculating such sums,
which may yield further evidence that the judgment isn't analytically true.

*** DONE Kant's ‘Copernican Revolution’
SCHEDULED: <2020-08-18 Tue>
:PROPERTIES:
:EXPORT_HUGO_TAGS: idealism cognition
:EXPORT_FILE_NAME: kant-copernican-revolution
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :toc true :type post :nocite '(@guyer2014 @allison2004 @gardner1999 @vancleve1999 @hogan2010)
:END:

**** The Copernican Turn

In a famous passage in the second edition of the /Critique of Pure Reason/ Kant
makes an analogy between the strategy pursued by his critical philosophy and
the central contribution of Nicolas Copernicus.

#+BEGIN_QUOTE
  Up to now it has been assumed that all our cognition must conform to
  the objects; but all attempts to find out something about them a
  priori through concepts that would extend our cognition have, on this
  presupposition, come to nothing. Hence let us once try whether we do
  not get farther with the problems of metaphysics by assuming that the
  objects must conform to our cognition, which would agree better with
  the requested possibility of an a priori cognition of them, which is
  to establish something about objects before they are given to us. This
  would be just like the first thoughts of Copernicus, who, when he did
  not make good progress in the explanation of the celestial motions if
  he assumed that the entire celestial host revolves around the
  observer, tried to see if he might not have greater success if he made
  the observer revolve and left the stars at rest. Now in metaphysics we
  can try in a similar way regarding the intuition of objects. (CPR
  Preface, Bxvi-xvii)
#+END_QUOTE

So just as Copernicus sought to explain the apparent motions of objects
in the heavens in terms of the movement of the earthbound observer, so
too Kant attempts to account for the apparent characteristics of objects
in terms of our cognitive faculties and the cognitive conditions under
which we know the objective world. In Kantian phrase, instead of
assuming that our knowledge of the object must conform to /it/, we
assume that it conforms to /our knowledge/.

**** Transcendental Idealism

Kant's name for the position he articulates according to which objects
must conform to our way of knowing them is ‘Transcendental Idealism.'
Though the exact meaning of Transcendental Idealism is much disputed by
Kant's interpreters, it is clear that he intends at least two things by
it.

First, according to Transcendental Idealism, space and time are neither
independent subsisting entities (as was suggested by Newton), nor
object-dependent orders of relations between entities (as was argued by
Leibniz). Instead, they are mind-dependent 'forms of intuition.' They are thus
understood in terms of the characteristic ways in which we experience things
rather than either being mind-independent things that we experience, or
relations between mind-independent things that we experience. Kant argues that
space and time are nevertheless 'empirically real' --- they are fundamental
features of the empirical world that we experience. But they are not real ‘in
themselves.' They have no ultimate reality apart from our capacity for
experience.

Second, in addition to the transcendental ideality of space and time, to
which all experienced objects must conform, Kant argues that empirical
reality is itself further structured by a privileged set of a priori concepts.

#+BEGIN_QUOTE
  experience itself is a kind of cognition requiring the understanding,
  whose rule I have to presuppose in myself before any object is given
  to me, hence a priori, which rule is expressed in concepts a priori,
  to which all objects of experience must therefore necessarily conform,
  and with which they must agree. As for objects insofar as they are
  thought merely through reason, and necessarily at that, but that (at
  least as reason thinks them) cannot be given in experience at all -
  the attempt to think them (for they must be capable of being thought)
  will provide a splendid touchstone of what we assume as the altered
  method of our way of thinking, namely that we can cognize of things a
  priori only what we ourselves have put into them (CPR Preface,
  Bxvii-xviii)
#+END_QUOTE

Kant here argues that the object which appear to one in perceptual
experience, or ‘intuition' as he calls it, also must conform to our
basic conceptual scheme. He explains what he means here in the last
sentence: objects must conform to our conceptual scheme because that
scheme makes possible the experience of such objects.

Though elements of Kant's ‘Copernican' strategy remain unclear,
the basic idea is that Kant argues that what makes synthetic a priori
knowledge possible is the structure of our cognitive faculties,
including the pure forms of intuition and a privileged set of a priori
concepts. These forms and concepts jointly make experience possible and
allow us to draw inferences that hold with necessity and universality
concerning objects encountered in experience. What's more, Kant argues
that because a priori concepts are necessary for experience in general,
we can know that those concepts are applied legitimately, since he is
taking it as obvious that we have experience.


* Configuration                                                                 :noexport:
#+HUGO_BASE_DIR: ./ 
#+STARTUP: nologdone
#+OPTIONS: H:4 author:nil date:nil
#+OPTIONS: prop:t preamble:nil
#+PANDOC_METADATA: numbersections:t secnumdepth:4 
#+PANDOC_METADATA: link-citations:t colorlinks:t toc:false 
#+PANDOC_METADATA: "lhead:"
#+PANDOC_METADATA: "mainfont:Optima"
#+PANDOC_METADATA: spacing:singlespacing 
#+PANDOC_METADATA: noindent: parskip:.85em
#+PANDOC_OPTIONS: template:~/.pandoc/pandoc-templates/tufteII.tex
#+PANDOC_OPTIONS: standalone:t pdf-engine:xelatex  
#+EXCLUDE_TAGS: notes scrap todo
#+BIBLIOGRAPHY: ~/Dropbox/Work/bibfile.bib

* Footnotes
* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
